apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kv-optkit.fullname" . }}
  labels:
    app: {{ include "kv-optkit.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kv-optkit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kv-optkit.name" . }}
    spec:
      containers:
        - name: kv-optkit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v in .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
