image:
  repository: ghcr.io/archokshi/kv-optkit
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}
