name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest requests matplotlib pandas fastapi uvicorn prometheus-client
      - name: Run tests
        run: pytest -q tests/test_metrics.py tests/test_report.py
      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t kv-optkit:test .
      - name: Smoke test container
        run: |
          docker run -d --rm -p 9000:9000 --name kvopt kv-optkit:test
          sleep 5
          curl -sf http://localhost:9000/healthz | jq .status
          curl -sf http://localhost:9000/metrics | head -n 5
          docker logs kvopt --tail 50 || true
          docker rm -f kvopt
